services:
  mongoku:
    image: huggingface/mongoku:latest
    container_name: mongoku
    ports:
      - "3100:3100"
    platform: linux/amd64
    volumes:
      - ./mongoku-connections.json:/app/connections.json
    environment:
      MONGOKU_DEFAULT_CONNECTIONS_FILE: "/app/connections.json"
    restart: unless-stopped
    networks:
      - scheduler-auth_default
      - scheduler-inventory_default
      - scheduler-requisicoes_default
      - scheduller-events_default


networks:
  scheduler-auth_default:
    external: true
  scheduler-inventory_default:
    external: true
  scheduler-requisicoes_default:
    external: true
  scheduller-events_default:
    external: true
