version: '3.3'

# Usage:
#   docker stack deploy -c stack.yml mongo
# or 
#   docker-compose -f stack.yml up

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-docker-k8s
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      #MONGODB_AUTH_DATABASE: admin
    ports:
      - "2003:27017"
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db
        
  mongo-express:
    image: mongo-express
    container_name: mongo-express-k8s
    restart: always
    ports:
      - "2001:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:2003/ # mongodb://mongoadmin:mongoadmin@127.0.0.1:2003/autenticacao?authSource=admin
      
    depends_on:
      - mongo

volumes:
  mongodb_data_volume:
    driver: local    
    