apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
spec:
  template:
    metadata:
      labels:
        app: kong-migrations
    spec:
      restartPolicy: Never
      containers:
        - name: kong-migrations
          image: kong/kong-gateway:latest
          command: ["kong", "migrations", "bootstrap"]
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "kong-database"
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              value: "kong"
            - name: KONG_PG_PASSWORD
              value: "kong"