apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: lmtp/custom-mongo-express:v01
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongo"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "changeme"
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "mongoadmin"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "mongoadmin"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  type: NodePort 
  ports:
    - protocol: TCP
      port: 8081         
      targetPort: 8081  
      nodePort: 31001    