apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-requisition
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scheduler-requisition
  template:
    metadata:
      labels:
        app: scheduler-requisition
    spec:
      containers:
        - name: app
          image: lmtp/scheduler-requisicoes:latest
          ports:
            - containerPort: 3023
          volumeMounts:
            - name: uploads-storage
              mountPath: /uploads 
          envFrom:
            - configMapRef:
                name: env-config-scheduler-requisition
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      volumes:
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: scheduler-requisition-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler-requisition-service
spec:
  selector:
    app: scheduler-requisition
  ports:
    - protocol: TCP
      port: 3023
      targetPort: 3023
  type: LoadBalancer