name: Docker Image CI

on:
  push:
    branches: 
      - "test"
  pull_request:
    branches: 
      - "test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (recommended for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (if pushing the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Install dependencies and run tests
      - name: Install dependencies and run tests
        run: |
          npm install
          npm test
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          SECRET_KEY: ${{ secrets.DOCKER_USERNAME }}
      # Step 5: Build the Docker image
      - name: Build the Docker image
        run: |
          IMAGE_TAG="lmtp/scheduler-auth:${GITHUB_SHA}"
          docker build . --file Dockerfile --tag $IMAGE_TAG

      # Step 6: Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_TAG="lmtp/scheduler-auth:${GITHUB_SHA}"
          docker push $IMAGE_TAG
          